name: Update submodules

on:
  schedule:
    - cron: "0 0 * * *" # run every day at midnight
  push:
    paths:
      - '*/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: |
          # Update all submodules
          git submodule update --init --recursive
          # Pull changes from the origin master branch for all submodules
          git submodule foreach git pull origin master
          # Check if there are any changes to commit
          if ! git diff-index --quiet HEAD --; then
            # Push changes to the main repository
            git config --global user.email "action@github.com"
            git config --global user.name "GitHub Action"
            git add .
            git commit -m "Update submodules"
            git push origin main
