name: Update submodules

on:
  push:
    paths:
      - '*/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Update submodules
        run: |
          # Check if the submodule has been updated
          if ! git diff --quiet HEAD -- submodule_directory; then
            # Update the submodule
            git submodule update --init --recursive
          fi
          # Pull changes from the origin master branch
          git pull origin master
      - name: Push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Update submodules"
          git push origin main

