name: Update Submodules

on:
  push:
    paths:
      - '**/*'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update Submodules
        run: |
          git submodule update --init --recursive
