name: Update Submodules

on:
  push:
    paths:
      - '**/*'

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Submodules
        run: |
          git submodule update --init --recursive
      - name: Push updated submodules to main repository
        uses: actions/github-script@v3
        with:
          github_token: ${{ secrets.GH_ACTIONS_TOKEN }}
          script: |
            git config user.email "actions@github.com"
            git config user.name "GitHub Actions"
            git push origin HEAD:${{ github.ref }}
